package main.java.cap.mapper

import cap.model.Article
import cap.model.ArticleWithBLOBs

interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    fun deleteByPrimaryKey(id: Int?): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    fun insert(record: ArticleWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    fun insertSelective(record: ArticleWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    fun selectByPrimaryKey(id: Int?): ArticleWithBLOBs

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    fun updateByPrimaryKeySelective(record: ArticleWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    fun updateByPrimaryKeyWithBLOBs(record: ArticleWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    fun updateByPrimaryKey(record: Article): Int
}