package main.java.cap.mapper

import cap.model.BlogInfo
import cap.model.BlogInfoWithBLOBs

interface BlogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    fun deleteByPrimaryKey(id: Int?): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    fun insert(record: BlogInfoWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    fun insertSelective(record: BlogInfoWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    fun selectByPrimaryKey(id: Int?): BlogInfoWithBLOBs

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    fun updateByPrimaryKeySelective(record: BlogInfoWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    fun updateByPrimaryKeyWithBLOBs(record: BlogInfoWithBLOBs): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbg.generated
     */
    fun updateByPrimaryKey(record: BlogInfo): Int
} }