package main.java.cap.mapper

import cap.model.Counter

interface CounterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbg.generated
     */
    fun deleteByPrimaryKey(id: Int?): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbg.generated
     */
    fun insert(record: Counter): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbg.generated
     */
    fun insertSelective(record: Counter): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbg.generated
     */
    fun selectByPrimaryKey(id: Int?): Counter

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbg.generated
     */
    fun updateByPrimaryKeySelective(record: Counter): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbg.generated
     */
    fun updateByPrimaryKey(record: Counter): Int
}