package main.java.cap.mapper

import cap.model.SysCategory

interface SysCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated
     */
    fun deleteByPrimaryKey(id: Int?): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated
     */
    fun insert(record: SysCategory): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated
     */
    fun insertSelective(record: SysCategory): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated
     */
    fun selectByPrimaryKey(id: Int?): SysCategory

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated
     */
    fun updateByPrimaryKeySelective(record: SysCategory): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_category
     *
     * @mbg.generated
     */
    fun updateByPrimaryKey(record: SysCategory): Int
}